version: '3.9'

services:
  backend:
    container_name: notify-automation-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: notify-automation-backend-image
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_worker:
    container_name: notify-automation-celery-worker
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: notify-automation-celery-worker-image
    command: celery -A app.celery_worker.celery_app worker --loglevel=info
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis
      - db
    restart: always

  db:
    container_name: notify-automation-db
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata-notify-automation:/var/lib/postgresql/data

  redis:
    container_name: notify-automation-redis
    image: redis:7
    restart: always
    ports:
      - "6378:6379"

volumes:
  pgdata-notify-automation:
